/**
 * ==============================================================================
 * EUREKA! 2026 REGISTRATION WEB APP - GOOGLE APPS SCRIPT BACKEND
 * Organized by Arya College of Engineering & I.T. & Arya Incubation Centre
 * ==============================================================================
 */

// Global Sheet Configuration
const SHEET_NAME = "Registrations";

// Optional: If Apps Script was created as a standalone script at script.google.com,
// paste your Google Sheet ID inside the quotes below:
const SPREADSHEET_ID = ""; 

/**
 * Handles incoming HTTP POST requests from the website submission fetch()
 */
function doPost(e) {
  // Acquire Script Lock to handle high-traffic concurrent submissions (50+ simultaneous users)
  const lock = LockService.getScriptLock();
  // Wait up to 30 seconds for other concurrent threads to release lock
  const success = lock.tryLock(30000);

  if (!success) {
    return ContentService.createTextOutput(JSON.stringify({
      status: "error",
      message: "Server is receiving high traffic. Please try submitting again in a few seconds."
    })).setMimeType(ContentService.MimeType.JSON);
  }

  try {
    let data;
    
    // Parse JSON payload or URL parameters
    if (e.parameter && e.parameter.payload) {
      try {
        data = JSON.parse(e.parameter.payload);
      } catch (err) {
        data = e.parameter;
      }
    } else if (e.postData && e.postData.contents) {
      try {
        data = JSON.parse(e.postData.contents);
      } catch (err) {
        data = e.parameter;
      }
    } else if (e.parameter) {
      data = e.parameter;
    } else {
      throw new Error("No data received in request.");
    }

    // Get Active Spreadsheet or open by SPREADSHEET_ID
    let ss;
    if (SPREADSHEET_ID && SPREADSHEET_ID.trim() !== "") {
      ss = SpreadsheetApp.openById(SPREADSHEET_ID.trim());
    } else {
      try {
        ss = SpreadsheetApp.getActiveSpreadsheet();
      } catch (err) {}
    }

    if (!ss) {
      throw new Error("Spreadsheet not found. Please paste your Google Sheet ID into SPREADSHEET_ID in Code.gs or create script inside Google Sheets via Extensions > Apps Script.");
    }

    let sheet = ss.getSheetByName(SHEET_NAME);

    // If "Registrations" sheet does not exist, create it
    if (!sheet) {
      sheet = ss.insertSheet(SHEET_NAME);
    }

    // Initialize Header Row if sheet is empty
    if (sheet.getLastRow() === 0) {
      const headers = [
        "Timestamp",
        "Registration ID",
        "Team Name",
        "Project Name",
        "Team Leader Name",
        "Leader Roll No",
        "Branch",
        "Section",
        "Year of Study",
        "Leader Mobile",
        "Leader Email",
        "Team Size",
        "Member 2 Name",
        "Member 2 Roll No",
        "Member 2 Branch",
        "Member 2 Section",
        "Member 2 Mobile",
        "Member 3 Name",
        "Member 3 Roll No",
        "Member 3 Branch",
        "Member 3 Section",
        "Member 3 Mobile",
        "Member 4 Name",
        "Member 4 Roll No",
        "Member 4 Branch",
        "Member 4 Section",
        "Member 4 Mobile",
        "Member 5 Name",
        "Member 5 Roll No",
        "Member 5 Branch",
        "Member 5 Section",
        "Member 5 Mobile",
        "Member 6 Name",
        "Member 6 Roll No",
        "Member 6 Branch",
        "Member 6 Section",
        "Member 6 Mobile",
        "Member 7 Name",
        "Member 7 Roll No",
        "Member 7 Branch",
        "Member 7 Section",
        "Member 7 Mobile",
        "Project Description"
      ];
      
      sheet.appendRow(headers);
      
      // Format Header Row (Bold, Background Color, Freeze)
      const headerRange = sheet.getRange(1, 1, 1, headers.length);
      headerRange.setFontWeight("bold");
      headerRange.setBackground("#0B4F9F");
      headerRange.setFontColor("#FFFFFF");
      sheet.setFrozenRows(1);
    }

    // Unique Registration ID (Use ID generated by frontend, or fallback to new ID)
    const timestamp = data.timestamp || new Date().toISOString();
    const formattedDate = Utilities.formatDate(new Date(), "Asia/Kolkata", "yyyy-MM-dd HH:mm:ss");
    const regId = data.registrationId || data.regId || ("EUR-2026-" + Math.floor(1000 + Math.random() * 9000));

    // Extract Team Leader Details
    const teamLeader = data.teamLeader || "";
    const leaderRollNo = data.leaderRollNo || "";
    const branch = data.branch || "";
    const section = data.section || "";
    const year = data.year || "";
    const mobile = data.mobile || "";
    const email = data.email || "";
    const teamName = data.teamName || "";
    const projectName = data.projectName || "N/A";
    const teamSize = data.teamSize || 1;

    // Extract Member 2 Details (supports both nested object & flat params)
    const m2 = data.member2 || {};
    const m2Name = m2.name || data.m2Name || "";
    const m2Roll = m2.rollNumber || data.m2Roll || "";
    const m2Branch = m2.branch || data.m2Branch || "";
    const m2Section = m2.section || data.m2Section || "";
    const m2Mobile = m2.mobile || data.m2Mobile || "";

    // Extract Member 3 Details
    const m3 = data.member3 || {};
    const m3Name = m3.name || data.m3Name || "";
    const m3Roll = m3.rollNumber || data.m3Roll || "";
    const m3Branch = m3.branch || data.m3Branch || "";
    const m3Section = m3.section || data.m3Section || "";
    const m3Mobile = m3.mobile || data.m3Mobile || "";

    // Extract Member 4 Details
    const m4 = data.member4 || {};
    const m4Name = m4.name || data.m4Name || "";
    const m4Roll = m4.rollNumber || data.m4Roll || "";
    const m4Branch = m4.branch || data.m4Branch || "";
    const m4Section = m4.section || data.m4Section || "";
    const m4Mobile = m4.mobile || data.m4Mobile || "";

    // Extract Member 5 Details
    const m5 = data.member5 || {};
    const m5Name = m5.name || data.m5Name || "";
    const m5Roll = m5.rollNumber || data.m5Roll || "";
    const m5Branch = m5.branch || data.m5Branch || "";
    const m5Section = m5.section || data.m5Section || "";
    const m5Mobile = m5.mobile || data.m5Mobile || "";

    // Extract Member 6 Details
    const m6 = data.member6 || {};
    const m6Name = m6.name || data.m6Name || "";
    const m6Roll = m6.rollNumber || data.m6Roll || "";
    const m6Branch = m6.branch || data.m6Branch || "";
    const m6Section = m6.section || data.m6Section || "";
    const m6Mobile = m6.mobile || data.m6Mobile || "";

    // Extract Member 7 Details
    const m7 = data.member7 || {};
    const m7Name = m7.name || data.m7Name || "";
    const m7Roll = m7.rollNumber || data.m7Roll || "";
    const m7Branch = m7.branch || data.m7Branch || "";
    const m7Section = m7.section || data.m7Section || "";
    const m7Mobile = m7.mobile || data.m7Mobile || "";

    // Extract Project Idea Description
    const projectDescription = data.projectDescription || "";

    // Construct Row Data Array
    const rowData = [
      formattedDate,
      regId,
      teamName,
      projectName,
      teamLeader,
      leaderRollNo,
      branch,
      section,
      year,
      mobile,
      email,
      teamSize,
      m2Name,
      m2Roll,
      m2Branch,
      m2Section,
      m2Mobile,
      m3Name,
      m3Roll,
      m3Branch,
      m3Section,
      m3Mobile,
      m4Name,
      m4Roll,
      m4Branch,
      m4Section,
      m4Mobile,
      m5Name,
      m5Roll,
      m5Branch,
      m5Section,
      m5Mobile,
      m6Name,
      m6Roll,
      m6Branch,
      m6Section,
      m6Mobile,
      m7Name,
      m7Roll,
      m7Branch,
      m7Section,
      m7Mobile,
      projectDescription
    ];

    // Append Row to Spreadsheet
    sheet.appendRow(rowData);

    // Return Success JSON Response
    const output = JSON.stringify({
      status: "success",
      message: "Registration recorded successfully",
      registrationId: regId,
      timestamp: formattedDate
    });

    return ContentService
      .createTextOutput(output)
      .setMimeType(ContentService.MimeType.JSON);

  } catch (error) {
    // Return Error JSON Response
    const errorOutput = JSON.stringify({
      status: "error",
      message: error.toString()
    });

    return ContentService
      .createTextOutput(errorOutput)
      .setMimeType(ContentService.MimeType.JSON);
  } finally {
    // Release the lock so the next waiting user can execute safely
    lock.releaseLock();
  }
}

/**
 * Handles HTTP GET requests to test endpoint health
 */
function doGet(e) {
  const result = JSON.stringify({
    status: "online",
    service: "Eureka! 2026 Registration Backend API",
    organization: "Arya College of Engineering & I.T. x Arya Incubation Centre",
    timestamp: new Date().toISOString()
  });

  return ContentService
    .createTextOutput(result)
    .setMimeType(ContentService.MimeType.JSON);
}
